### ISSUE TITLE
Is not working.

### ISSUE THREAD

**Issue by Erick2297** [Wolf49406/Dota2Patcher#32]
Hi, before anything, amazing work.
Don't know why Dota plus does not want to work. It says it's unlocked but when you open dota, nothing.
Also, I'll like to learn how you do it, how you know what are the bytes you need to change and what software do you use.

**Comment by Wolf49406** [comment]
Because it does literally nothing atm. I need more time to fix my cheat after 7.32b. Then i'll find a new way to unlock dota+.
https://github.com/Wolf49406/Dota2Patcher/blob/master/Patcher.cpp#L69
>how you know what are the bytes you need to change  

Just a regular reverse engineering. C++, assembler, tons of practice. 
https://github.com/No-Bling/DOTA/issues/76#issuecomment-1014974809

**Comment by Erick2297** [comment]
Ok, thank you. Didn't see that.
